language: python
python:
- '3.6'
install:
- pip install -q ansible molecule apache-libcloud
before_script:
- ansible --version && ansible-lint --version && molecule --version
script:
- echo OK
notifications:
  slack:
    rooms:
      secure: Ix1wlwSkvzjglQ6JzvjGKSoc1ibDWhoYZuLd3qCFm6E+S2TEmJqWXRJaJOLdpixQwCcXd9Sv8C4IG71Pi/XaBzfFCjy54mboGypoyXvBhyL3rd6pwWKHRrF30SL8EjrxlKOIYiSmSoTZqbf7czxkqeWZJRcjekR41Y61A80peu2r1XP39je2riq468QKLKec84Mxgp8qFHffkwK4Zu6uw7v6XQKDwSsMC/+AsxzS+9/kDKd4/WNy1ro0jCG8hD2mFT9tDM3IZqR8E5/DnYcKr1uZ5t3WPPuvmqxdymc7YfQEvMIwKIFUIrw3XXNVM6L9UNHMY4DXBst32ISGlJWqfJ3DMBKiIqTIEU1YB8S5bG4A/+tA1NB4CjQ7HKQPiKOd25bs+4lJqnS7hDRYDjCrCbcwnLqj+IXEsDfNI4ZL3KF0bbu82A0JgLnR7zH0CSaxzoHy2QxRd6OYzZXV79LTQYYr+iNyO2dFBNBt0BZljZOFkfqkS0U8gfs5pcXIlV2QyvOsTs0VxSCFJGdsbrfkkc46huU1gzlkm1Y2UuB6YGxJFLPkKddUtSZHSgbywrLceQPVAutJtupHEOJfQN55qth01o7rUoHKsFXjRMMv4gO++2sxsecKN6T3J5s7xoFj1VoE26De1Fyi+v7Bvo0ijIkMp43w+Pc+eIws48UO5oI=
