---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance-for-travis
    zone: europe-north1-a
    machine_type: f1-micro
    image_family: ubuntu-1604-lts
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
